import test from 'node:test';import assert from 'node:assert/strict';import {reconcile,move,indent,parse,agentContext,checkAgentPatch} from './model.mjs';
const source=[['r',0],['a',1],['b',1],['c',1],['d',2]].map(([uuid,depth])=>({uuid,depth,content:uuid}));
test('view subtree move leaves source intact and preserves children',()=>{const before=JSON.stringify(source),items=reconcile([],source);const next=move(items,'c','a');assert.deepEqual(next.map(x=>x.uuid),['r','c','d','a','b']);assert.equal(JSON.stringify(source),before);assert.deepEqual(move(next,'c','d','child'),next)});
test('indent and outdent whole subtree, root immovable',()=>{const items=reconcile([],source),nested=indent(items,'c',1);assert.equal(nested.find(x=>x.uuid==='c').depth,2);assert.equal(nested.find(x=>x.uuid==='d').depth,3);assert.deepEqual(indent(nested,'c',-1),items);assert.deepEqual(move(items,'r','b'),items);assert.deepEqual(move(items,'a','r'),items)});
test('source edits/reorder/insertion/removal/resurrection do not reorder existing references',()=>{const saved=move(reconcile([],source),'c','a');let updated=reconcile(saved,[source[0],source[2],{uuid:'x',depth:2,content:'new'},source[1]]);assert.deepEqual(updated.filter(x=>x.uuid!=='x'),saved);assert.equal(updated.find(x=>x.uuid==='x').depth,2);assert.deepEqual(reconcile(updated,source),updated)});
test('compatible personal markers and orthogonal task state',()=>{for(const label of ['现状','问一下','注','想法'])for(const text of [`【${label}】 正文`,`[${label}] 正文`,`**[${label}]** 正文`])assert.equal(parse(text).role,label);assert.equal(parse('TODO 【问一下】 交期？').task,'TODO');assert.equal(parse('TODO 【问一下】 交期？').kind,'question');assert.equal(parse('**[注]** 需要拉表核对').task,null);assert.equal(parse('**[想法]** 可以先测试').task,null)});
test('no semantics from code, page refs, quotation, non-prefix and unfinished labels',()=>{for(const t of ['[[想法]]','`TODO 假任务`','> TODO 引用','正文中【注】','```\nTODO 代码\n```']){assert.equal(parse(t).role,null);assert.equal(parse(t).task,null)}assert.equal(parse('【问一').incomplete,true);assert.equal(parse('【问一').role,null)});
test('agent sees source parent and presentation separately; stale and editing rejected',()=>{const s={graph:'g',root:'r',rows:source,draft:null,instance:'one',seq:2},p={graph:'g',uuid:'a',expectedContent:'a'};assert.equal(checkAgentPatch(s,p),'eligible-for-review');assert.equal(checkAgentPatch({...s,draft:'a'},p),'source-editing');assert.equal(checkAgentPatch(s,{...p,expectedContent:'old'}),'stale-source');assert.equal(checkAgentPatch(s,{...p,graph:'other'}),'graph-mismatch');assert.equal(checkAgentPatch(s,{...p,uuid:'gone'}),'source-missing');const ctx=agentContext(s,move(reconcile([],source),'b','a','child'));assert.equal(ctx.blocks.find(x=>x.uuid==='b').sourceParent,null);assert.equal(ctx.presentation.find(x=>x.uuid==='b').depth,2)});
test('300 nodes / 2000 source updates preserve customized layout',()=>{const big=Array.from({length:300},(_,i)=>({uuid:'b'+i,depth:i===0?0:1,content:'【注】'+i}));const order=move(reconcile([],big),'b250','b3','child');for(let i=0;i<2000;i++){big[i%300].content+='x';assert.deepEqual(reconcile(order,big),order)}});

test('agent operation depending on source parent is invalidated by source reparenting',()=>{const s={graph:'g',rows:[{uuid:'a',content:'TODO test',sourceParent:'new'}],draft:null};assert.equal(checkAgentPatch(s,{graph:'g',uuid:'a',expectedContent:'TODO test',expectedSourceParent:'old'}),'source-parent-changed')});
