// Actual plugin controller with a stub SDK; no browser or synthetic DOM assertions.
import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {createRequire} from 'node:module';
let require=createRequire(import.meta.url);try{require.resolve('esbuild')}catch{require=createRequire('/Users/wangrundong/work/任务管理中心-logseq插件/package.json')}
const {build}=require('esbuild');
const result=await build({entryPoints:['plugin.ts'],bundle:true,write:false,format:'iife',platform:'browser',define:{RUNTIME:JSON.stringify({port:8768,token:'test'})},plugins:[{name:'view-stub',setup(b){b.onResolve({filter:/^\.\/render$/},()=>({path:'view',namespace:'stub'}));b.onLoad({filter:/.*/,namespace:'stub'},()=>({contents:`export function render(s,l,h){globalThis.latest=s;globalThis.handlers=h} export const referencedIds=()=>[];export const layoutState=()=>({});export const getViewState=()=>globalThis.latest;export const applyViewOp=()=>({ok:true});`,loader:'js'}))}}]});
const fixture={m:{uuid:'m',content:'**[MiniProject]** #MiniProject M',parent:{id:'p'},page:{id:'p'}},a:{uuid:'a',content:'**[任务]** A',parent:{id:'m'},page:{id:'p'}},n:{uuid:'n',content:'普通说明',parent:{id:'a'},page:{id:'p'}},b:{uuid:'b',content:'**[事项]** B',parent:{id:'p'},page:{id:'p'}}};
async function start(){const events={},store=new Map();const cx={console,URL,Date,Promise,Map,Set,JSON,crypto:{randomUUID:()=> 'instance'},setTimeout:()=>0,clearTimeout(){},setInterval:()=>0,clearInterval(){},requestAnimationFrame:f=>f(),fetch:async()=>({}),EventSource:class{close(){}},localStorage:{getItem:k=>store.get(k)??null,setItem:(k,v)=>store.set(k,v)},document:{getElementById:()=>null}};
 cx.window={parent:{document:{addEventListener:(type,fn)=>events[type]=fn,removeEventListener(){}}}};
 cx.logseq={ready:fn=>cx.ready=fn(),beforeunload(){},provideStyle(){},setMainUIInlineStyle(){},showMainUI(){},hideMainUI(){},UI:{showMsg(){}},Editor:{getBlock:async id=>fixture[id]??null,getCurrentPage:async()=>({originalName:'fixture'}),checkEditing:async()=>null},App:{getCurrentGraph:async()=>({path:'fixture'}),registerCommand(){},registerCommandPalette(){},onCurrentGraphChanged(){}},DB:{onChanged(){}}};
 vm.runInNewContext(result.outputFiles[0].text,cx);await cx.ready;
 return {cx,events,click:id=>events.click({target:{closest:()=>({getAttribute:()=>id})}})};}
const deferred=()=>{let resolve;return {promise:new Promise(r=>resolve=r),resolve:v=>resolve(v)}};
test('native click handler accepts ordinary block; stale parent read cannot overwrite newer click',async()=>{const {cx,click}=await start();const gate=deferred();const original=cx.logseq.Editor.getBlock;let once=true;cx.logseq.Editor.getBlock=async id=>{if(id==='n'&&once){once=false;await gate.promise}return original(id)};
 const old=click('n');await click('b');assert.equal(cx.latest.root,'b');gate.resolve();await old;assert.equal(cx.latest.root,'b');await click('n');assert.equal(cx.latest.root,'a');assert.deepEqual(Array.from(cx.latest.objectChain,x=>x.uuid),['m','a']);});
test('slow page lookup cannot commit a superseded object',async()=>{const {cx,click}=await start();const gate=deferred(),reached=deferred();let once=true;cx.logseq.Editor.getCurrentPage=async()=>{if(once){once=false;reached.resolve();await gate.promise}return {originalName:'fixture'}};
 const old=click('n');await reached.promise;await click('b');gate.resolve();await old;assert.equal(cx.latest.root,'b');});
test('breadcrumb pin ignores internal ordinary clicks, explicit enter clears it, external leaves',async()=>{const {cx,click}=await start();await click('n');await cx.handlers.onCrumb('m');assert.equal(cx.latest.held,'breadcrumb');await click('n');assert.equal(cx.latest.root,'m');await cx.handlers.onEnter('a');assert.equal(cx.latest.root,'a');assert.equal(cx.latest.held,null);await cx.handlers.onCrumb('m');await click('b');assert.equal(cx.latest.root,'b');assert.equal(cx.latest.held,null)});
test('ancestor rename publishes fresh breadcrumb even when scope/body/focus stay unchanged',async()=>{const {cx,click}=await start();await click('n');const saved=fixture.m.content;try{fixture.m.content='**[MiniProject]** #MiniProject Renamed';await click('n');assert.equal(cx.latest.objectChain[0].title,'Renamed');assert.equal(cx.latest.rows[0].sourceParent,'m')}finally{fixture.m.content=saved}});
