import { readFile, lstat } from "node:fs/promises";
import { createHash, randomUUID } from "node:crypto";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { ClientError } from "@task-copilot/client";
import { WorkspaceError, parseWorkspaceDescriptor, parseWorkBinding, sameWorkScope, workRecord, workText, type WorkspaceCommand, type WorkspaceCall, type WorkspaceDescriptor } from "@task-copilot/contracts";
import { option, required, type CliIO } from "./cli.ts";
import { startWorkspaceServer } from "./workspace-server.ts";
export const workspaceHelp = `Task Copilot natural workspace CLI (local connection; no Kernel required)
  workspace serve [--state-dir <private-directory>]  # foreground; stop with Ctrl+C
  workspace status | capabilities | refresh | read
  workspace source read <sourceId>
  workspace guidance read | collaboration read | collaboration refresh
  # Explicitly load the returned guidance versions. A saved scene can be stale; inspect current before writing.
  workspace files list | read <relative-path> | associate <relative-path>
  workspace materials list | read <id> | capture --input-file <path|->
  workspace materials associate --path <relative-path> | --id <materialId>
  workspace materials resolve --path <relative-path>
  workspace materials save --input-file <path|->
  workspace focus request --question <text> | source | read | apply --input-file <path|-> | cancel | exit | back
  workspace reading request --purpose <text> | read | submit --input-file <path|-> | select <planId> | original
  workspace reading cancel <requestId> | highlight --input-file <path|-> | clear
  # Reading plans carry source IDs/versions and finite layouts; never replacement text or writing/TODO grants.
  workspace content read | pending | apply --input-file <path|-> | result <requestId> | recover <requestId> | retry --input-file <path|->
  workspace todo read | apply --input-file <path|-> | result <requestId> | recover <requestId> | resumeIdentity <requestId> | retry --input-file <path|->
  workspace formatting preview --input-file <path|-> | result <requestId> | recover <requestId>
  # Preview only. The user reviews and applies the exact limited prefix diff in Logseq; no external approval/apply flag.
  # Independent local range/action grant; complete requires current material version and exact evidence text. Formal operations remain forbidden.
  # move-block uses content.apply or stage.submit, patch schemaVersion:2; inspect capabilities first.
  # Requires local "允许 agent 润色并整理当前工作原块"; text-only permission never grants moves.
  workspace sessions list | add --platform <name> --session-id <id> [--url <real-link>] [--description <text>] | remove --platform <name> --session-id <id>
  workspace stage read --input-file <path|->  # JSON: {stageId}; unavailable without installed provider
  workspace stage submit --input-file <path|->  # same local stage; no approval
  --directory <work-directory> (default cwd; finds nearest WORKSPACE.md + agent locator)
  --state-dir <private-directory> (default TASK_COPILOT_WORKSPACE_STATE or ~/.task-copilot-workspace)
  --client <session-label> (default TASK_COPILOT_WORKSPACE_CLIENT or shell; use distinct labels for independent sessions)
  --request-id <stable-transport-id> --json
Read is always last-known. Refresh contacts Logseq. JSON plans and patches are generated by the agent from actual source versions, not filled in by the user.`;
export async function privateDescriptor(path: string): Promise<WorkspaceDescriptor> {
    const stat = await lstat(path);
    if (!stat.isFile() || stat.isSymbolicLink() || stat.size > 8192 || (process.platform !== "win32" && ((stat.mode & 0o077) !== 0 || stat.uid !== process.getuid?.())))
        throw new WorkspaceError("DESCRIPTOR_NOT_PRIVATE");
    return parseWorkspaceDescriptor(JSON.parse(await readFile(path, "utf8"))) as WorkspaceDescriptor;
}
export async function workspaceEntry(directory: string): Promise<{
    directory: string;
    instanceId: string;
    connectionId: string;
    binding: ReturnType<typeof parseWorkBinding>;
}> {
    let current = resolve(directory);
    for (let depth = 0; depth < 16; depth++) {
        const path = join(current, ".task-workspace", "agent-connection.json");
        try {
            const stat = await lstat(path);
            if (!stat.isFile() || stat.isSymbolicLink() || stat.size > 16384)
                throw new WorkspaceError("WORKSPACE_ENTRY_INVALID");
            const metadata = await lstat(join(current, ".task-workspace"));
            if (!metadata.isDirectory() || metadata.isSymbolicLink())
                throw new WorkspaceError("WORKSPACE_ENTRY_INVALID");
            const raw = workRecord(JSON.parse(await readFile(path, "utf8")), ["schemaVersion", "instanceId", "connectionId", "binding"]);
            if (raw.schemaVersion !== 1)
                throw new WorkspaceError("WORKSPACE_ENTRY_INVALID");
            const binding = parseWorkBinding(raw.binding);
            if (binding.directory !== current)
                throw new WorkspaceError("WORKSPACE_ENTRY_INVALID");
            // Registry remains the schema owner. This projection only checks entry identity;
            // online scope authority is independently checked in the plugin.
            let entryFile = "WORKSPACE.md";
            if (binding.provider === "workspace") {
                const manifestPath = join(current, ".task-workspace", "manifest.json"), info = await lstat(manifestPath);
                if (!info.isFile() || info.isSymbolicLink() || info.size > 256000)
                    throw new WorkspaceError("WORKSPACE_MANIFEST_INVALID");
                const manifest = JSON.parse(await readFile(manifestPath, "utf8"));
                if (manifest.schemaVersion !== 1 || manifest.workspaceId !== binding.workspaceId || !manifest.primarySource || !sameWorkScope(manifest.primarySource, binding.scope) || manifest.organization !== binding.organization || typeof manifest.entryFile !== "string" || !/^WORKSPACE(?:\.[a-z0-9-]+)?\.md$/u.test(manifest.entryFile))
                    throw new WorkspaceError("WORKSPACE_MANIFEST_MISMATCH");
                entryFile = manifest.entryFile;
            }
            const entry = await lstat(join(current, entryFile));
            if (!entry.isFile() || entry.isSymbolicLink())
                throw new WorkspaceError("WORKSPACE_ENTRY_INVALID");
            return { directory: current, instanceId: workText(raw.instanceId), connectionId: workText(raw.connectionId), binding };
        }
        catch (error) {
            if ((error as {
                code?: string;
            }).code !== "ENOENT")
                throw error;
        }
        const parent = dirname(current);
        if (parent === current)
            break;
        current = parent;
    }
    throw new WorkspaceError("WORKSPACE_NOT_BOUND", "No active local workspace entry found. Bind a directory and allow this work in Logseq.");
}
export async function workspaceHttp(descriptor: WorkspaceDescriptor, call: WorkspaceCall, timeout = 25000): Promise<unknown> {
    let response: Response;
    try {
        response = await fetch(`${descriptor.baseUrl}/call`, { method: "POST", redirect: "error", headers: { "content-type": "application/json", authorization: `Bearer ${descriptor.token}`, "x-workspace-instance": descriptor.instanceId }, body: JSON.stringify(call), signal: AbortSignal.timeout(timeout) });
    }
    catch {
        throw new WorkspaceError("CHANNEL_UNAVAILABLE", "Local channel unavailable or timed out. A delivered write may have an unknown outcome; query its original request before retrying.");
    }
    const body = await response.json() as {
        instanceId?: string;
        value?: unknown;
        error?: {
            code: string;
            message: string;
        };
    };
    if (!response.ok)
        throw new WorkspaceError(body.error?.code ?? "CHANNEL_FAILED", body.error?.message);
    if (body.instanceId !== descriptor.instanceId)
        throw new WorkspaceError("DESCRIPTOR_STALE");
    const value = body.value;
    return value && typeof value === "object" && "provenance" in value && "value" in value ? value.value : value;
}
export async function runWorkspaceCli(args: string[], io: CliIO): Promise<number> {
    const json = args.includes("--json");
    try {
        if (args.includes("--help") || args.includes("-h") || args.length === 1) {
            io.out(workspaceHelp);
            return 0;
        }
        const valueFlags = new Set(["--state-dir", "--directory", "--client", "--request-id", "--input-file", "--question", "--purpose", "--path", "--id", "--platform", "--session-id", "--url", "--description"]), words: string[] = [];
        for (let index = 0; index < args.length; index++) {
            const arg = args[index]!;
            if (valueFlags.has(arg)) {
                required(args, arg);
                index++;
            }
            else if (arg === "--json")
                continue;
            else if (arg.startsWith("-"))
                throw new ClientError("CLI_USAGE", `Unknown option ${arg}`, 2);
            else
                words.push(arg);
        }
        const state = resolve(option(args, "--state-dir") ?? process.env.TASK_COPILOT_WORKSPACE_STATE ?? join(homedir(), ".task-copilot-workspace"));
        if (words.join(" ") === "workspace serve") {
            if (process.platform === "win32")
                throw new WorkspaceError("PRIVATE_TRANSPORT_UNSUPPORTED", "First release requires POSIX private descriptor permissions.");
            const service = await startWorkspaceServer({ stateDirectory: state });
            io.out(JSON.stringify({ status: "listening", pluginDescriptorPath: service.pluginDescriptorPath, tasksRequired: false }));
            await new Promise<void>(yes => { const close = () => { process.removeListener("SIGINT", close); process.removeListener("SIGTERM", close); void service.close().then(yes); }; process.on("SIGINT", close); process.on("SIGTERM", close); });
            return 0;
        }
        const entry = await workspaceEntry(option(args, "--directory") ?? process.cwd());
        const commandWords = words.slice(1);
        if (commandWords[0] === "capabilities")
            commandWords[0] = "status";
        let command: WorkspaceCommand, payload: Record<string, unknown> = {};
        const pair = commandWords.slice(0, 2).join(".");
        const input = async () => {
            const path = required(args, "--input-file");
            if (!io.readInput)
                throw new ClientError("CLI_USAGE", "Input reader unavailable", 2);
            const text = await io.readInput(path);
            let raw: unknown;
            try {
                raw = JSON.parse(text);
            }
            catch {
                throw new ClientError("CLI_RESULT_JSON_INVALID", "Input must contain valid JSON", 2);
            }
            return raw;
        };
        if (commandWords.length === 1 && ["status", "refresh", "read"].includes(commandWords[0]!))
            command = commandWords[0] as WorkspaceCommand;
        else if (["todo.read","guidance.read","collaboration.read","collaboration.refresh","files.list", "materials.list", "focus.source", "focus.read", "focus.cancel", "focus.exit", "focus.back", "reading.read", "reading.original", "reading.clear", "content.read", "content.pending", "sessions.list"].includes(pair) && commandWords.length === 2)
            command = pair as WorkspaceCommand;
        else if (["formatting.result","formatting.recover","todo.result","todo.recover","todo.resumeIdentity","files.read", "files.associate", "materials.read", "source.read", "content.result", "content.recover"].includes(pair) && commandWords.length === 3) {
            command = pair as WorkspaceCommand;
            payload = { [pair.startsWith("files") ? "path" : pair === "source.read" ? "sourceId" : pair.startsWith("content")||pair.startsWith("todo")||pair.startsWith("formatting") ? "requestId" : "id"]: commandWords[2] };
        }
        else if (pair === "focus.request" && commandWords.length === 2) {
            command = pair;
            payload = { question: required(args, "--question") };
        }
        else if(pair==="reading.request"&&commandWords.length===2) {command=pair;payload={purpose:required(args,"--purpose")};}
        else if(["reading.select","reading.cancel"].includes(pair)&&commandWords.length===3) {
            command=pair as WorkspaceCommand;payload={[pair==="reading.select"?"planId":"requestId"]:commandWords[2]};
        }
        else if (pair === "materials.associate" && commandWords.length === 2) {
            command = pair;
            payload = option(args, "--id") ? { id: required(args, "--id") } : { path: required(args, "--path") };
        }
        else if (pair === "materials.resolve" && commandWords.length === 2) {
            command = pair; payload = {path: required(args, "--path")};
        }
        else if (pair==="formatting.preview"&&commandWords.length===2){command=pair;payload=workRecord(await input(),["requestId","sourceIds","labels"]);}
        else if (["todo.apply","todo.retry","focus.apply", "reading.submit", "reading.highlight", "content.apply", "content.retry", "materials.capture", "materials.save", "stage.read", "stage.submit"].includes(pair) && commandWords.length === 2) {
            command = pair as WorkspaceCommand;
            const raw = await input();
            payload = pair==="todo.apply"?{request:raw}:pair==="todo.retry"?workRecord(raw,["previousRequestId","request"]):pair === "focus.apply"||pair==="reading.submit" ? { plan: raw } : pair === "content.apply" ? { patch: raw } : pair.startsWith("stage")||pair==="reading.highlight" ? { input: raw } : workRecord(raw, pair === "content.retry" ? ["previousRequestId", "patch"] : pair === "materials.save" ? ["id", "expectedVersion", "expectedContent", "next"] : ["requestKey", "text", "html", "title", "role"]);
        }
        else if (["sessions.add", "sessions.remove"].includes(pair) && commandWords.length === 2) {
            command = pair as WorkspaceCommand;
            payload = { platform: required(args, "--platform"), externalId: required(args, "--session-id"), ...(option(args, "--url") ? { url: required(args, "--url") } : {}), ...(option(args, "--description") ? { description: required(args, "--description") } : {}) };
        }
        else
            throw new ClientError("CLI_USAGE", "Unknown workspace command; use workspace --help", 2);
        if (command === "read") {
            const path = join(state, `last-known-${createHash("sha256").update(JSON.stringify((entry.binding as {
                directory: string;
            }).directory)).digest("hex")}.json`);
            const cached = JSON.parse(await readFile(path, "utf8"));
            if (JSON.stringify(parseWorkBinding(cached.binding)) !== JSON.stringify(entry.binding))
                throw new WorkspaceError("CACHE_SCOPE_MISMATCH");
            io.out(JSON.stringify({ freshness: "last-known", sourceAvailable: false, snapshot: cached.snapshot, binding: cached.binding, workspace: cached.workspace ? { ...cached.workspace, freshness: "last-known" } : null }));
            return 0;
        }
        const descriptor = await privateDescriptor(join(state, "workspace.json"));
        if (descriptor.instanceId !== entry.instanceId)
            throw new WorkspaceError("DESCRIPTOR_STALE", "Entry belongs to a previous channel; allow the work again locally.");
        const call: WorkspaceCall = { schemaVersion: 1, instanceId: descriptor.instanceId, connectionId: entry.connectionId, clientId: option(args, "--client") ?? process.env.TASK_COPILOT_WORKSPACE_CLIENT ?? "shell", requestId: option(args, "--request-id") ?? randomUUID(), command, payload };
        const value = await workspaceHttp(descriptor, call);
        io.out(JSON.stringify(value, null, json ? undefined : 2));
        return 0;
    }
    catch (error) {
        const code = error instanceof WorkspaceError || error instanceof ClientError ? error.code : "WORKSPACE_OPERATION_FAILED", message = error instanceof Error ? error.message : String(error);
        io.err(json ? JSON.stringify({ error: { code, message } }) : `${code}: ${message}`);
        return error instanceof ClientError && error.status === 2 ? 2 : 1;
    }
}
